# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 03:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('porte', models.CharField(max_length=50)),
                ('idade', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to=b'')),
                ('ponto', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
