# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 06:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='ponto',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
